---
- hosts: localhost
  become: true
  tasks:
    - include: "tasks/last-run.yaml"
    - include: "tasks/backup-dot-files.yaml"
    - include: "tasks/dot-files.yaml"
    - include: "tasks/software/cli-utils.yaml"
    # - include: "tasks/software/vs-code.yaml" # Doesn't work in Docker
    - include: "tasks/software/chrome.yaml"
    - include: "tasks/software/development-tools.yaml"
