- name: Install Chrome - key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
- name: Install Chrome - repo
  apt_repository:
    repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    update_cache: yes
- name: Install Chrome
  apt:
    pkg: google-chrome-stable
- name: Install Brave - key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    state: present
- name: Install Brave - repo
  apt_repository:
    # ??? somehow at this point a accrued a warning (or maybe running the above twice, or file renaming?)
    # W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list:1 and /etc/apt/sources.list.d/google-chrome.list:3
    repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
    update_cache: yes
- name: Install Brave
  apt:
    pkg: brave-browser
- name: Install Firefox
  apt:
    pkg: firefox
