- name: Install Chrome - key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
- name: Install Chrome - repo
  apt_repository:
    repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    update_cache: yes
- name: Install Chrome
  apt:
    pkg: google-chrome-stable
- name: Install Brave - key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    state: present
- name: Install Brave - repo
  apt_repository:
    repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
    update_cache: yes
- name: Install Brave
  apt:
    pkg: brave-browser
